.base:
  variables:
    APCI_ALPAKA_ROOT: "$CI_PROJECT_DIR"
    APCI_RUN_CTEST: ON
    APCI_HIP : 0
    APCI_CUDA : 0
  script:
    - $APCI_ALPAKA_ROOT/script/ci/job_info.sh
    - $APCI_ALPAKA_ROOT/script/ci/install_dependencies.sh
    - $APCI_ALPAKA_ROOT/script/ci/configure.sh
    - $APCI_ALPAKA_ROOT/script/ci/build.sh
    - $APCI_ALPAKA_ROOT/script/ci/test.sh
  tags:
  - x86_64
  - cpuonly

.cuda:
  extends: .base
  image: ubuntu:24.04
  variables:
    APCI_CMAKE: 3.28.3
  tags:
  - x86_64
  - cuda

gcc-13:
  image: docker.io/ubuntu:24.04
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : gcc@13
    APCI_CMAKE: 3.28.3

gcc-15:
  image: docker.io/ubuntu:24.04
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : gcc@15
    APCI_CMAKE: 3.28.3

gcc-12-agc:
  image: registry.hzdr.de/crp/alpaka-group-container/alpaka-ci-ubuntu24.04-gcc:4.0
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : gcc@12
    APCI_CMAKE: 3.31.4

clang-19:
  image: docker.io/ubuntu:24.04
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : clang@19
    APCI_CMAKE: 3.28.3

clang-21:
  image: docker.io/ubuntu:24.04
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : clang@21
    APCI_CMAKE: 3.28.3

clang-20-agc:
  image: registry.hzdr.de/crp/alpaka-group-container/alpaka-ci-ubuntu24.04-gcc:4.0
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : clang@20
    APCI_CMAKE: 3.31.4

hipcc-7.0:
  image: ubuntu:24.04
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : clang@20
    APCI_CMAKE: 3.31.4
    APCI_HIP : 7.0

hipcc-7.2-agc:
  image: registry.hzdr.de/crp/alpaka-group-container/alpaka-ci-ubuntu24.04-gcc:4.0
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : clang@22
    APCI_CMAKE: 3.28.3
    APCI_HIP : 7.2

hipcc-6.3-agc:
  image: registry.hzdr.de/crp/alpaka-group-container/alpaka-ci-ubuntu24.04-rocm6.3:addubuntu2204cudacontainer-4.0
  extends: .base
  variables:
    APCI_DEVICE_COMPILER : clang@21
    APCI_CMAKE: 3.28.3
    APCI_HIP : 6.3

# TODO: remove number jobs after I checked that all CUDA SDK versions can be installed
cuda-12.5-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@12.5
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 12.5

cuda-12.6-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@12.6
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 12.6

cuda-12.8-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@12.8
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 12.8

cuda-12.8-clang:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@12.8
    APCI_HOST_COMPILER: clang@19
    APCI_CUDA: 12.8

cuda-12.9-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@12.9
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 12.9

cuda-13.0-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@13.0
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 13.0
  tags:
  - x86_64
  - cuda
  - a100

cuda-13.1-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@13.1
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 13.1
  tags:
  - x86_64
  - cuda
  - a100

cuda-13.2-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@13.2
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 13.2
  tags:
  - x86_64
  - cuda
  - a100

cuda-13.3-gcc:
  extends: .cuda
  variables:
    APCI_DEVICE_COMPILER: nvcc@13.3
    APCI_HOST_COMPILER: gcc@13
    APCI_CUDA: 13.3
  tags:
  - x86_64
  - cuda
  - a100
